# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-11 11:40
from __future__ import unicode_literals

from django.db import migrations


def _migrate_desktop_user_to_os_user(apps, schema_editor):
    DesktopUser = apps.get_model("kolibri_desktop_auth_plugin", "DesktopUser")
    OSUser = apps.get_model("device", "OSUser")
    for desktop_user in DesktopUser.objects.all():
        # Unfortunately, DesktopUser refers to a user by uid, while OSUser
        # refers to a user by username. So, we will guess that the desktop
        # user's username is the same as the Kolibri user's username, which is
        # the default behaviour except for unusual circumstances.
        OSUser.objects.update_or_create(
            os_username=desktop_user.user.username,
            defaults={"user": desktop_user.user},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("kolibri_desktop_auth_plugin", "0001_initial"),
        ("device", "0016_osuser"),
    ]

    operations = [
        migrations.RunPython(_migrate_desktop_user_to_os_user),
        migrations.DeleteModel("DesktopUser"),
    ]
